downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-01.csv.gz to data/raw///01/_tripdata__01.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-02.csv.gz to data/raw///02/_tripdata__02.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-03.csv.gz to data/raw///03/_tripdata__03.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-04.csv.gz to data/raw///04/_tripdata__04.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-05.csv.gz to data/raw///05/_tripdata__05.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-06.csv.gz to data/raw///06/_tripdata__06.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-07.csv.gz to data/raw///07/_tripdata__07.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-08.csv.gz to data/raw///08/_tripdata__08.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-09.csv.gz to data/raw///09/_tripdata__09.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-10.csv.gz to data/raw///10/_tripdata__10.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-11.csv.gz to data/raw///11/_tripdata__11.csv.gz
downloading https://github.com/DataTalksClub/nyc-tlc-data/releases/download//_tripdata_-12.csv.gz to data/raw///12/_tripdata__12.csv.gz
